name: revise_right
description: A Flutter app for smart revision scheduling
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  
  # Notifications
  # flutter_local_notifications: ^16.3.0
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Optional
  flutter_quill: ^11.5.0
  
  # AI Integration
  http: ^1.1.0
  google_generative_ai: ^0.4.7
  
  # Charts
  fl_chart: ^0.65.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - .env